### ISSUE TITLE
4.1 Missing

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-sarjus#10]
👋 Hi @sarjus you are missing the Module 4.1 Assignment. Please post it here in this thread.

**Comment by sarjus** [comment]
@arelia 
**Describe the existing technical student communities on your campus. Who is served? Where are there gaps?**
In our campus we have a Free and Open Source Cell ( FOSS Cell). We are conducting different peer to peer learning sessions and Student Development Programs under this cell. We have student from different Under Graduate streams as members of this community. The current Gap is we don’t have a platform to collaborate the students, so that they can work as a team to develop projects.
**Choose one GitHub Education program. How could it support your on-campus student communities?**
The effective use of GitHub tool boxes to collaboratively engage the students communities. I am really amazed with the range of tools provided by GitHub. Definitely we will use the tool box effectively.
**What would you need to do in order to support the growth of student tech communities on campus?**
We need to conduct Hackathons, it will help the student communities to apply the skills they learned from different platforms.
